services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tasks'
      - 'POSTGRES_PASSWORD=s3cr3t'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'